services:
  postgres:
    image: postgres:16
    container_name: collab_poc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: collab_poc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - collab_poc_pg_data:/var/lib/postgresql/data

volumes:
  collab_poc_pg_data:
